/*
db/seeds/03_stories.sql
*/

INSERT INTO stories (content, title, author_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed molestie tincidunt ipsum ac hendrerit. Donec id libero at quam facilisis pharetra eget in urna. Etiam sed nibh iaculis, auctor urna id, efficitur quam. Nunc quis pharetra lectus. Duis id augue dapibus, bibendum justo in, blandit metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed porttitor quam. Cras dapibus dictum est, eget porttitor ex gravida in. Curabitur cursus nisi sed justo egestas tempor. Curabitur cursus mi laoreet est finibus, id lacinia quam ornare. Morbi porta iaculis arcu, in dignissim metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis orci metus, convallis facilisis congue et, facilisis sit amet nisi. Donec eget mauris sit amet purus eleifend vehicula. Etiam efficitur ac nibh sed sollicitudin. Aliquam commodo augue leo, sed accumsan neque euismod eget. Nulla sit amet sapien commodo, laoreet nibh sit amet, dictum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nec ligula nec justo viverra interdum at vitae orci. Vestibulum euismod lacinia est, sit amet luctus ipsum facilisis tristique. Aliquam in tortor eu risus laoreet feugiat. Morbi blandit maximus metus at aliquam.

Phasellus vitae magna a ex convallis auctor. Fusce leo est, venenatis ac aliquam vitae, volutpat et velit. Vivamus id justo volutpat ex dictum semper ut ut leo. Aliquam purus metus, lacinia quis ligula et, laoreet accumsan ex. Ut commodo, nibh vel accumsan convallis, est lectus mattis enim, sed tincidunt libero justo at tellus. Quisque venenatis eleifend eros, a rhoncus orci. Proin ut ex sed velit tincidunt porta.', 'Lorem Ipsum Dolor', 1);

INSERT INTO stories (content, title, author_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut consequat nunc. Morbi vestibulum, augue sed suscipit feugiat, neque velit consequat eros, quis vulputate metus felis ut quam. Aenean id posuere diam. Quisque vel luctus nibh. Aliquam porta turpis ipsum, nec laoreet odio sollicitudin ac. Cras ut dignissim odio, et sollicitudin quam. Suspendisse nulla turpis, cursus sit amet ultricies in, gravida vel dolor. Suspendisse a felis sodales, ultricies lectus non, viverra mauris. Praesent molestie felis ut felis sodales maximus. Cras varius nibh et nisl placerat, quis imperdiet est aliquam. Nulla at mattis dui. Sed vulputate bibendum posuere.

Integer tincidunt dui et malesuada molestie. Suspendisse vehicula sollicitudin sollicitudin. Ut nec nunc in urna commodo maximus eget eget sem. Nulla tempus felis ut nulla ornare, vitae mollis justo suscipit. Donec justo arcu, tincidunt ac convallis ac, suscipit eu tellus. Nulla ullamcorper pulvinar tempus. Donec posuere porttitor nunc. Maecenas in feugiat nunc. Curabitur et mi sagittis, auctor sem eu, facilisis ante. Suspendisse sit amet scelerisque nisl. Vivamus viverra placerat nisl eu ultricies. Curabitur ut aliquet neque, nec sagittis neque. Suspendisse rutrum pretium malesuada. Quisque consequat eget erat congue feugiat.

Nam porttitor ipsum diam, ut tempus nulla cursus ut. Donec vel eros aliquet lorem pellentesque aliquam ac eget dolor. Curabitur tincidunt ligula nec magna dignissim, sed convallis est viverra. Vivamus vulputate ex sem, eget ornare sapien sagittis vel. Integer a augue lacus. Maecenas id aliquam sapien, ac tempor enim. Quisque rutrum sapien augue, a imperdiet velit hendrerit ornare. Nullam non velit ut mauris posuere porttitor vitae in diam. Donec facilisis erat ut posuere tempor. Aliquam quis efficitur nulla.

Suspendisse feugiat sit amet dolor eget accumsan. Morbi sit amet turpis mi. Suspendisse potenti. Cras pellentesque, massa vitae cursus finibus, massa est tincidunt enim, a tincidunt mauris risus egestas quam. In hac habitasse platea dictumst. Nunc vestibulum sed sapien eget ultricies. Maecenas justo enim, venenatis scelerisque semper non, commodo ut metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis lacinia leo magna, ut iaculis tellus pellentesque in. Praesent pharetra lacus nec ornare varius. Praesent lobortis sagittis consequat. Vivamus convallis volutpat dapibus. Sed a faucibus risus. Integer id arcu at odio iaculis tempus quis nec augue. Proin ut nisl non metus interdum egestas ac vel magna.', 'Consectetur Adipiscing Elit', 2);

INSERT INTO stories (content, title, author_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non congue nunc. Proin mauris urna, consectetur sed ipsum ac, lacinia dictum nibh. Quisque at ligula vitae ipsum faucibus pharetra convallis in lectus. Aenean ut efficitur massa, mollis egestas mauris. Nam feugiat eros turpis, sed finibus neque ultricies vel. Phasellus ornare, turpis eget consequat dignissim, enim erat dignissim metus, non malesuada metus dui pharetra felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus leo, consectetur ut leo ac, tincidunt dictum dui. Integer tempor maximus lorem, viverra tincidunt sem pulvinar ultrices.

Vestibulum eget odio ut ipsum varius mattis. Quisque feugiat porta dictum. Sed a lorem vitae ante mattis tincidunt. Aenean congue, ante quis rutrum imperdiet, tortor ipsum porttitor sem, et cursus tortor ante ut purus. Sed viverra tristique purus, quis facilisis lorem rutrum at. Sed pellentesque interdum facilisis. Mauris pretium, ex eu interdum porta, dolor nisi semper metus, vitae tempus quam eros sed nunc. Phasellus sollicitudin convallis augue, quis molestie ante feugiat sit amet. Sed egestas egestas risus nec euismod. Phasellus interdum nisi in massa tempor ultrices. Vivamus vel augue et sem malesuada venenatis. Donec quis nulla vitae lacus varius blandit. Integer ac consectetur tortor. Nullam a vulputate nibh. Sed hendrerit ullamcorper ultricies. Pellentesque risus tortor, aliquam vel tristique vitae, dignissim iaculis leo.', 'Aliquam Fringilla Nibh Vita', 3);

INSERT INTO stories (state, content, title, author_id) VALUES ('Complete', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non congue nunc. Proin mauris urna, consectetur sed ipsum ac, lacinia dictum nibh. Quisque at ligula vitae ipsum faucibus pharetra convallis in lectus. Aenean ut efficitur massa, mollis egestas mauris. Nam feugiat eros turpis, sed finibus neque ultricies vel. Phasellus ornare, turpis eget consequat dignissim, enim erat dignissim metus, non malesuada metus dui pharetra felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus leo, consectetur ut leo ac, tincidunt dictum dui. Integer tempor maximus lorem, viverra tincidunt sem pulvinar ultrices.

Vestibulum eget odio ut ipsum varius mattis. Quisque feugiat porta dictum. Sed a lorem vitae ante mattis tincidunt. Aenean congue, ante quis rutrum imperdiet, tortor ipsum porttitor sem, et cursus tortor ante ut purus. Sed viverra tristique purus, quis facilisis lorem rutrum at. Sed pellentesque interdum facilisis. Mauris pretium, ex eu interdum porta, dolor nisi semper metus, vitae tempus quam eros sed nunc. Phasellus sollicitudin convallis augue, quis molestie ante feugiat sit amet. Sed egestas egestas risus nec euismod. Phasellus interdum nisi in massa tempor ultrices. Vivamus vel augue et sem malesuada venenatis. Donec quis nulla vitae lacus varius blandit. Integer ac consectetur tortor. Nullam a vulputate nibh. Sed hendrerit ullamcorper ultricies. Pellentesque risus tortor, aliquam vel tristique vitae, dignissim iaculis leo.

Sed egestas egestas risus nec euismod. Phasellus interdum nisi in massa tempor ultrices. Vivamus vel augue et sem malesuada venenatis. Donec quis nulla vitae lacus varius blandit. Integer ac consectetur tortor. Nullam a vulputate nibh. Sed hendrerit ullamcorper ultricies. Pellentesque risus tortor, aliquam vel tristique vitae, dignissim iaculis leo.', 'Aliquam Nibh Vita', 3);

INSERT INTO stories (state, content, title, author_id) VALUES ('Complete', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non congue nunc. Proin mauris urna, consectetur sed ipsum ac, lacinia dictum nibh. Quisque at ligula vitae ipsum faucibus pharetra convallis in lectus. Aenean ut efficitur massa, mollis egestas mauris. Nam feugiat eros turpis, sed finibus neque ultricies vel. Phasellus ornare, turpis eget consequat dignissim, enim erat dignissim metus, non malesuada metus dui pharetra felis.

Vestibulum eget odio ut ipsum varius mattis. Quisque feugiat porta dictum. Sed a lorem vitae ante mattis tincidunt. Aenean congue, ante quis rutrum imperdiet, tortor ipsum porttitor sem, et cursus tortor ante ut purus. Sed viverra tristique purus, quis facilisis lorem rutrum at. Sed pellentesque interdum facilisis. Mauris pretium, ex eu interdum porta, dolor nisi semper metus, vitae tempus quam eros sed nunc. Phasellus sollicitudin convallis augue, quis molestie ante feugiat sit amet. Sed egestas egestas risus nec euismod. Phasellus interdum nisi in massa tempor ultrices. Vivamus vel augue et sem malesuada venenatis. Donec quis nulla vitae lacus varius blandit. Integer ac consectetur tortor. Nullam a vulputate nibh. Sed hendrerit ullamcorper ultricies. Pellentesque risus tortor, aliquam vel tristique vitae, dignissim iaculis leo.

Sed egestas egestas risus nec euismod. Phasellus interdum nisi in massa tempor ultrices. Vivamus vel augue et sem malesuada venenatis. Donec quis nulla vitae lacus varius blandit. Integer ac consectetur tortor. Nullam a vulputate nibh. Sed hendrerit ullamcorper ultricies. Pellentesque risus tortor, aliquam vel tristique vitae, dignissim iaculis leo.', 'Feugiat Vivamus', 1);
